name = "hex-real-roots-mathlib"
defaultTargets = ["HexRealRootsMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "v0.8.0"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "v0.8.0"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "v0.8.0"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "v0.8.0"

[[require]]
name = "HexRealRoots"
git = "https://github.com/leanprover/hex-real-roots.git"
rev = "v0.8.0"

[[require]]
name = "TauCeti"
git = "https://github.com/TauCetiProject/TauCeti.git"
rev = "1c497c347f615b3087cb605f8cf743e591376105"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6b7abb3c7686292736be2955bd3eb9ebf63b456a"

[[lean_lib]]
name = "HexRealRootsMathlib"

[[lean_lib]]
name = "HexRealRootsMathlibTests"
globs = ["HexRealRootsMathlib.IsolateRootsTests", "HexRealRootsMathlib.IsolateRootsElabTests", "HexRealRootsMathlib.SturmTests", "HexRealRootsMathlib.RealRootCountTests", "HexRealRootsMathlib.TarskiTests"]
