name = "hex-real-roots-mathlib"
defaultTargets = ["HexRealRootsMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRealRoots"
git = "https://github.com/leanprover/hex-real-roots.git"
rev = "e52b424fd9ad6ccb186a1048ca644622ba5b6c1e"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "781fcf515411217c4e03e4f607ce8a84ef818bcb"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "d4bbb82b87704d3016c6c1d822ae1f77c793958a"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexRealRootsMathlib"

[[lean_lib]]
name = "HexRealRootsMathlibTests"
globs = ["HexRealRootsMathlib.IsolateRootsTests", "HexRealRootsMathlib.IsolateRootsElabTests"]
